### ISSUE TITLE
InfoHash is empty for and Unable to resolve .torrent file at

### ISSUE THREAD

**Issue by maxdd** [mancuniancol/script.magnetic.nyaa-mc#1]
Hello,
Here i am again with your great work.

Below it is a problem when using nyaa and Dragon as query (it happens with all the torrents)
The funny thing is that the torrents link in the log are working.
http://pastebin.com/zDTqb9CY

i'm using quasar 0.9.35

**Comment by mancuniancol** [comment]
I've found the problem.  However, I will ask you next time to publish the complete log in debug mode.  There is plenty information there that it makes easier to find the problem.

I've releasing version 0.4.1 with the fix.  Please, let me know if that works for you.
